name: build-focal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Initiate Build
        run: |
          cd scripts
          ./build.sh -

      - name: List Build
        run: |
          ls -hl scripts/
          mv scripts/ubuntu-from-scratch.iso scripts/regolith-linux-1.6.0.iso

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          files: |
            scripts/regolith-linux-1.6.0.iso
