name: build-hirsute

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build ISO
        run: |
          cd scripts
          cp config-hirsute.sh config.sh
          ./build.sh -

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest-hirsute"
          files: |
            scripts/regolith-linux-hirsute-1.6.0.iso
