name: build-focal-legacy-boot

on:
  push:
    branches: [ master ]
    paths:
      - 'scripts/config-focal_legacy_boot.sh'
      - 'scripts/chroot_build.sh'
      - 'scripts/build.sh'
  pull_request:
    branches: [ master ]
    paths:
      - 'scripts/config-focal_legacy_boot.sh'
      - 'scripts/chroot_build.sh'
      - 'scripts/build.sh'
  workflow_dispatch:
concurrency: 
  group: ubuntu-iso-build
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build ISO
        run: |
          cd scripts
          cp config-focal_legacy_boot.sh config.sh
          ./build.sh -

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "regolith-linux-focal-legacy-boot-latest"
          files: |
            scripts/Regolith_1.6.0_focal.iso
