name: build-impish

on:
  push:
    branches: [ master ]
    paths:
      - 'scripts/config-impish_standard.sh'
      - 'scripts/chroot_build.sh'
      - 'scripts/build.sh'
  pull_request:
    branches: [ master ]
    paths:
      - 'scripts/config-impish_standard.sh'
      - 'scripts/chroot_build.sh'
      - 'scripts/build.sh'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build ISO
        run: |
          cd scripts
          cp config-impish_standard.sh config.sh
          ./build.sh -

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "regolith-linux-2.0-impish-latest"
          files: |
            scripts/*.iso
