name: build-focal

on:
  push:
    branches: [ master ]
    paths:
      - 'scripts/config-focal.sh'
  pull_request:
    branches: [ master ]
    paths:
      - 'scripts/config-focal.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build ISO
        run: |
          cd scripts
          cp config-focal.sh config.sh
          ./build.sh -

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "regolith-linux-focal-latest"
          files: |
            scripts/regolith-linux-focal-1.6.0.iso
