name: build-bionic

on:
  push:
    branches: [ master ]
    paths:
      - 'scripts/config-bionic.sh'
      - 'scripts/chroot_build.sh'
      - 'scripts/build.sh'
  pull_request:
    branches: [ master ]
    paths:
      - 'scripts/config-bionic.sh'
      - 'scripts/chroot_build.sh'
      - 'scripts/build.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build ISO
        run: |
          cd scripts
          cp config-bionic.sh config.sh
          ./build.sh -

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "regolith-linux-bionic-latest"
          files: |
            scripts/regolith-linux-bionic-1.6.0.iso
